### ISSUE TITLE
add this to pub.dev packages

### ISSUE THREAD

**Issue by X-SLAYER** [ibrierley/flutter_map_line_editor#1]
thank you for this amazing package! but can you add it to pub.dev packages because when I try to install it , it show me error because I use others dependencies that use flutter_map from pub.dev not from GitHub like u use in this package

**Comment by ibrierley** [comment]
Heya, sorry I missed this issue, never got a notification. Can you explain a bit more what needs to be added and where, and what error you get so I can replicate if it's still an issue ?

**Comment by X-SLAYER** [comment]
basically this plugin use flutter_map from git, not as a package so when I use another package thas already use flutter_map from pub.dev like map_controller it gives me an error

**Comment by ibrierley** [comment]
Thanks, I had completely missed that. See if that's any better.
