### ISSUE TITLE
How do you compute the area of the polygon?

### ISSUE THREAD

**Issue by scolar** [ibrierley/flutter_map_line_editor#15]

**Comment by ibrierley** [comment]
Does this help ?

https://pub.dev/packages/area

or

https://stackoverflow.com/questions/16285134/calculating-polygon-area#:~:text=The%20formula%20(X%5Bj%5D%2B,of%20the%20%22downgoing%22%20edges.

**Comment by scolar** [comment]
It helped me，thank you
