### ISSUE TITLE
Non-nullable instance field 'polyEditor' must be initialized.

### ISSUE THREAD

**Issue by yechta** [ibrierley/flutter_map_line_editor#16]
I get this error whenever I try to run the code.

How can I solve this? Thank you.

**Comment by ibrierley** [comment]
Are you trying the nullsafe branch ?

**Comment by yechta** [comment]
Yes, I added the latest version

**Comment by ibrierley** [comment]
How are you trying to initialise it, do you have some example code, and have you tried running the examples ?
