### ISSUE TITLE
Performance issues

### ISSUE THREAD

**Issue by princebb** [ibrierley/flutter_map_line_editor#2]
This code '**polyLines.add(testPolyline);**' should not be placed in build(), because the build() method will be called multiple times, which will cause the testPolyline to be added multiple times and it can be placed in initState().
When multiple points are drawn and dragged several times, the map operation will become quite slow

**Comment by ibrierley** [comment]
Thanks for that, it was only the test example, but it should encourage others not to just copy the code :D. See if that's better.
