### ISSUE TITLE
Can support polygon ?

### ISSUE THREAD

**Issue by zozeei** [ibrierley/flutter_map_line_editor#3]

**Comment by ibrierley** [comment]
I suspect it can support them. Basically it just takes a list of points, which it changes in place.

If that list is then used to draw a polygon, I think it shouldn't care. The code doesn't care what anything is, other than a list of points to change.

Give it a go and let me know if it doesn't work.

**Comment by zozeei** [comment]
I followed your suggestion.  But only points show up, no line connecting those points (as in the picture). Do you know how can I fix this problem?

**Comment by ibrierley** [comment]
Is it possible to do a barebones minimal example showing the issue.

I don't think you'd get lines, as that's only if you are using
polylines.....if you are using a polygon and using those points (it must be
the exact same list of points, not a copy, as it edits in place). I would
expect you to get markers where your polygon points are (and midway along
the polygon edge), but I've never tried it with polygons. I am happy to
poke about and take a look though....

Thanks,

Ian
