### ISSUE TITLE
Make it compatible with latlong2 0.8.1 as in dragmarker

### ISSUE THREAD

**Issue by Y0ngg4n** [ibrierley/flutter_map_line_editor#30]
@ibrierley https://github.com/ibrierley/flutter_map_line_editor/pull/29

**Comment by ibrierley** [comment]
flutter_map_line_editor is currently broken for the latest release, I thought I had resolved this, but the updates I did aren't there (it's due to updates in dragmarker), so I'll have to revisit this first I think. So I don't recommend updating to the latest version of this currently...I will try and sort all of this as soon as I get time and update latlong2 at the same time if all ok.

**Comment by Y0ngg4n** [comment]
so i can´t use dragmarker with 3.0.0?

**Comment by ibrierley** [comment]
You can use dragmarker with 3.0.0, you can't use line_editor with it though...I have a fix almost ready, but keep getting issues. I think you may find line_editor works from pub.dev, but not from git (but git needs to be fixed before latlng2 0.8.1 can be used...).

**Comment by ibrierley** [comment]
Well, technically I think I've updated it. But I think there are some subtle bugs with it, and I'm not sure if these are quick or difficult fixes (looking at intermediate icons and their positions aren't exact enough on web for my liking and there's been a lot of changes with dragmarker, flutter_map v3, flutter v3 etc).

I'll be honest, I'm not sure how much time I've got to work on this currently, so it may be good enough, but I may retire the plugin if I don't think I can give enough time to properly maintain it.

**Comment by Y0ngg4n** [comment]
Maybe just publish the changes and handle the bugs via issues if they occure. So we have anything to work with.

**Comment by ibrierley** [comment]
Yes, it's been published so feel free to test. Thinking about it, I suspect the bug is possibly that the mid points need a proper latlng calculation which will vary depending on zoom level, which is something that can be worked on.

**Comment by Y0ngg4n** [comment]
@ibrierley Thank you. take your time. Nobody expects from you to do anything. But would be sad if you do not longer maintain this project because it is great.
