### ISSUE TITLE
Markers not dragging - again

### ISSUE THREAD

**Issue by Mmisiek** [ibrierley/flutter_map_line_editor#33]
Hi Ian,
We went thought this issue 2 years ago but now with updated Fluter and Map (3.0) I had problem to run LineEditor.
Originally I was using DragMaker from the package but they changed interface to I switched to yours.
It does compile but dragging does not work anymore ?
`flutter_map_line_editor: ^4.0.2
flutter_map_dragmarker: ^4.1.2 
`

Thanks for help in advance.

**Comment by Mmisiek** [comment]
Ian, my bad I was missing
` absorbPanEventsOnScrollables: false,`
in MapOptions, I guess it was added in last year ?
Thanks for great plugin !

**Comment by ibrierley** [comment]
Yes, I think that was switched at some point, can't remember when, thanks for the feedback.
