### ISSUE TITLE
Next version

### ISSUE THREAD

**Issue by andim27** [ibrierley/flutter_map_line_editor#40]
Please add support for flutter_map ^6.0.0  
Because flutter_map_dragmarker >=5.0.0 depends on flutter_map ^5.0.0 and flutter_map_dragmarker <5.0.0 depends on latlong2 ^0.8.0, every version of flutter_map_dragmarker requires flutter_map
  ^5.0.0 or latlong2 ^0.8.0.

**Comment by JWambaugh** [comment]
I am also having this issue.

**Comment by ibrierley** [comment]
Should be updated as of a few days ago, shout if any issues
