### ISSUE TITLE
Problem with editing line segment

### ISSUE THREAD

**Issue by zozeei** [ibrierley/flutter_map_line_editor#5]
Hi,

I am having trouble editing the last line segment of the polygon (line connecting point 1 and 3) for it cannot be extended or bent. Do you have a suggestion for fixing this problem?
![polygon](https://user-images.githubusercontent.com/49703843/92590226-0b954600-f2c6-11ea-809f-7f04f4006cd8.gif)

**Comment by ibrierley** [comment]
It's not very clear from the image....in the issue you raised a few days ago, you were able to add points, so I'm wondering what you have that's different now ?

**Comment by zozeei** [comment]
Sorry, the image I sent was not very clear. I am sending a new one. The issue is that I cannot drag (edit) the line segment of point 1 and 3.
![Screenshot_1599701875](https://user-images.githubusercontent.com/49703843/92671629-f90c2280-f340-11ea-8868-47f548afb10a.png)

**Comment by ibrierley** [comment]
Ah yes, I think that makes sense logically, as there is no actual end point back to the start, it's assumed there is sort of an extra one inferred back to the beginning which it can't see.

Not quite sure the best way to handle that, as I'd prefer it not to know any underlying line or shape and just handle a set of points, but maybe there could be an option to infer an extra line back to the beginning. I'll have a ponder, but probably won't get chance to have a play for a day or so. In the interim, I guess you can add an extra point by dragging between 2 and 3, but that's a bit clunky to have to move the last bit each time, so does feel like it could do with something there to help.

**Comment by ibrierley** [comment]
Ok, I've added an option addClosePathMarker : true/false. Set to true if you want the extra marker on a closed final section like a closed polygon. Set to false if a line. See if that helps.

**Comment by zozeei** [comment]
Thank you very much for your help! It's working fine now. I've changed from 0 to 2 in this line of code so that it can handle polygon type
![1599789706108](https://user-images.githubusercontent.com/49703843/92843817-5b335900-f40f-11ea-92dd-47dbf0c78ef5.jpg)

**Comment by ibrierley** [comment]
Ok thanks, what happened if the check > 0 was left instead of 2 out of interest (it makes sense for it to be > 2), were there duplicate markers on the first leg or something ?

**Comment by zozeei** [comment]
Yes, there duplicate markers on the first leg

**Comment by ibrierley** [comment]
Super, thanks for the update. I'll add that change to git.
