### ISSUE TITLE
Make icons be widgets?

### ISSUE THREAD

**Issue by moovida** [ibrierley/flutter_map_line_editor#9]
Hi, would it be possible to let the handler icons be widgets? That would make it possible to have better visible effects for example by stacking 2 different color icons.

**Comment by ibrierley** [comment]
I think that seems reasonable...I'm not sure if it's as simple as changing the icon an pointIcon type from an Icon to a Widget. Feel free to see if that works in the meantime (not quite sure atm when I'll get chance to test).

**Comment by moovida** [comment]
@ibrierley , yes it should be that simple. They are wrapped in a container anyways so they are handled as widgets.

Also tested to be sure:
```
class PolyEditor {
  final List points;
  final Widget pointIcon;
  final Widget intermediateIcon;
```

**Comment by ibrierley** [comment]
Great, thanks. Feel free to make a pull request (pretty new to git repos, so will give me practice!), otherwise I'll update over the weekend.

**Comment by moovida** [comment]
Oh, ok, will be happy to do so. Didn't want to dirty your repo with two lines of code. :-) 
Will do right away, thanks

**Comment by moovida** [comment]
Here it is: #10
Thank you
